# Generated by Django 4.0.6 on 2022-08-12 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbers', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('appointmentId', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('serviceType', models.CharField(max_length=250)),
                ('appointDate', models.CharField(max_length=250)),
                ('appointTime', models.CharField(max_length=250)),
                ('amount', models.CharField(max_length=250)),
                ('barberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbers.barber')),
                ('custId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'db_table': 'appointments',
            },
        ),
    ]
