# Generated by Django 4.0.6 on 2022-08-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='barber',
            fields=[
                ('barberId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=250)),
                ('lastName', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('phoneNumber', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('age', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'barber',
            },
        ),
    ]
